---
- name: install enable and run apache webserver
  hosts: all
  tasks:
  - name: install 
    yum:
      name: httpd
      state: latest
  - name: run and enable
    service:
      name: httpd
      state: started
      enabled: true
  - name: open firewall
    firewalld:
      service: http
      permanent: yes
      state: enabled
